import SmoothScrollProvider from "./utils/SmoothScrollProvider";

export const metadata = {
  title: "R2MI Logistics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScrollProvider>
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
